version: "3.7"
services:
  torq:
    image: "lncapital/torq:latest"
    restart: on-failure
    depends_on:
      - "db"
    command:
      - --db.host
      - db
      - --db.password
      - <YourDBPassword> # Must match db password below
      - --torq.password
      - <YourUIPassword> # Set password here to connect to login to the web ui
      - --torq.port
      - "<YourPort>"
      - start
    ports:
      - "<YourPort>:<YourPort>"
  db:
    image: "timescale/timescaledb:latest-pg14"
    environment:
      POSTGRES_PASSWORD: <YourDBPassword> # Must match db password set above
    volumes:
      - torq_db:/var/lib/postgresql/data
volumes:
  torq_db:
